### ISSUE TITLE
Doing .serialize() changes the UNA segment

### ISSUE THREAD

**Issue by kashyapm94** [nerdocs/pydifact#11]
I am running the following code:

```
from pydifact.message import Message
from pydifact.segments import Segment

INVOIC = Message()

def UNA():
    INVOIC.add_segment(Segment('UNA', ":+.? '"))

UNA()

result = INVOIC.serialize()
```

As you can see in the `UNA` segment, I have **:+.? '** and this gets converted to **:+,? '** when I run the `.serialize()` line.

I don't want the '.' to get converted to a ','. Is there a way around to stop this from happening?

**Comment by nerdoc** [comment]
I'll look into this.

**Comment by nerdoc** [comment]
I saw that there is a problem in serialize(). It misinterprets the `with_una` parameter a bit. I ask myself now: is there a use for serializing segments, **without** printing the UNA header?

Would it be a possibility to just add the header if missing?

**Comment by nerdoc** [comment]
Fixed. Now the character set is respected.

**Comment by nerdoc** [comment]
@kashyapm94 Please tell me if it works for you with the newest version.

**Comment by kashyapm94** [comment]
Hey,

I am trying to run the same piece of code in both Spyder and in VSCode and I observe the following:

1. When running in spyder, the . still gets converted to ,

2. When running in VScode, the . remains unchanged.

It's weird. Do you think running in different IDEs effect the output?

**Comment by nerdoc** [comment]
No. Please make sure that you really are running the correct version  of pydifact in Spyder. Sometimes it uses another path, with still the old cached version? If I find time, I'll upload a new version to pypi.
